# This pod mounts the nfs volume claim into /usr/share/nginx/html and
# serves a simple web page.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: afs-web
spec:
  replicas: 2
  selector:
    matchLabels:
      role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      containers:
      - name: web
        image: evillgenius/pv-web:v1.3
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            # name must match the volume name below
            - name: afs
              mountPath: "/usr/share/nginx/html/dyn"
      volumes:
      - name: afs
        persistentVolumeClaim:
          claimName: afs
---
kind: Service
apiVersion: v1
metadata:
  name: afs-web
spec:
  ports:
    - port: 80
  selector:
    role: web-frontend
  type: LoadBalancer