# This mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: afs-writer
spec:
  replicas: 2
  selector:
    matchLabels:
      name: afs-writer
  template:
    metadata:
      labels:
        name: afs-writer
    spec:
      containers:
      - image: alpine
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/dyn.html; "\n" >> /mnt/dyn.html; hostname >> /mnt/dyn.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          # name must match the volume name below
          - name: afs
            mountPath: "/mnt"
      volumes:
      - name: afs
        persistentVolumeClaim:
          claimName: afs